apiVersion: v1
kind: PersistentVolume
metadata:
  name: insource-pv-001
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /insource-data-001/
    type: DirectoryOrCreate