apiVersion: v1
kind: PersistentVolume
metadata:
  name: <insource-pv-name>
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /<insource-data-path>/
    type: DirectoryOrCreate