apiVersion: kustomize.config.k8s.io/v1beta1  
kind: Kustomization  

# Include the base directory  
bases:  
  - ../../base/

resources:  
  - namespace.yml   
  - insource-pv.yml  
  - postgres-pv.yml  
  - insource-pvc.yml  
  - postgres-pvc.yml 
 
namespace: <insource-namespace>

patchesStrategicMerge:  
  - patch-postgres-deployment.yml
  - patch-insource-api-deployment.yml
  - patch-admin-api-deployment.yml
  - patch-ingress.yml