apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: admin-ui
  namespace: insource
spec:  
  template:  
    spec:  
      containers:  
      - name: admin-ui
        env:
          - name: INSOURCE_CHAT_HOST
            value: "<insource-ingress-host>/<overlay_folder_name>/api"
          - name: INSOURCE_ADMIN_HOST
            value: "<insource-ingress-host>/<overlay_folder_name>/admin-api"