apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: postgres-pv-claim  
  namespace: <insource-namespace>
spec:
  volumeName: <postgres-pv-name>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 