apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-insource-data 
  namespace: insource1
spec:
  volumeName: <insource-pv-name>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 