apiVersion: v1
kind: PersistentVolume
metadata:
  name: <postgres-pv-name>
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /<postgres-data-path>/
    type: DirectoryOrCreate