apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-insource-data 
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /insource-data/
    type: DirectoryOrCreate