apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /insource-postgres/
    type: DirectoryOrCreate