apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: postgres-pv-claim  
  namespace: insource
spec:
  volumeName: postgres-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 