apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-insource-data 
  namespace: <insource-namespace>
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: <insource-pv-name>
  resources:
    requests:
      storage: 1Gi