apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: postgres-pv-claim  
  namespace: <insource-namespace>
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: <postgres-pv-name>
  resources:
    requests:
      storage: 1Gi